# Generated by Django 4.0.6 on 2022-07-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_familia_delete_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
