# Generated by Django 4.0.6 on 2022-07-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_familia_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familia',
            new_name='Familiares',
        ),
    ]
