# Generated by Django 4.0.6 on 2022-07-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_familia_familiares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
