# Generated by Django 4.0.6 on 2022-07-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
    ]
